[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 800
via_ir = true
ffi = true

fs_permissions = [
  { access = "read", path = "./" },
  { access = "read-write", path = ".forge-snapshots/" }
]

[profile.default.rpc_endpoints]
sepolia-eth = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"